@host = http://localhost:7071

### person.index
GET {{host}}/api/person

### person.index
GET {{host}}/api/person?name=放浪軍師

### person.index
GET {{host}}/api/person?name=夏狂乱

### person.index
GET {{host}}/api/person?name=放浪軍師&name=name2

### person.index
GET {{host}}/api/person?provider=provider

### person.show
GET {{host}}/api/person/id/e66e343a-5e2f-4053-8e2b-1185e8faef88

### person.delete
DELETE {{host}}/person/person/id/569b5d23-569a-4325-9164-12198991f869

### person.store
POST {{host}}/api/person

{
    "name": "放浪軍師",
    "job": "エンジニア",
    "attributes": [
        "変態","天才","変人"
    ],
    "items":[
        {
            "name": "デスクトップパソコン",
            "content": "VRやるためにそこそこのしたヤツ"
        },
        {
            "name": "ノートパソコン",
            "content": "乱ちゃんのシールが貼ってあるMACPC"
        }        
    ]
}

### person.store
POST {{host}}/api/person

{
    "name": "夏狂乱",
    "job": "アプリケーション",
    "attributes": [
        "ランダム","マルチプラットフォーム","抽選"
    ],
    "items":[
        {
            "name": "サイコロ",
            "content": "髪飾りに2個付いている"
        },
        {
            "name": "巫女服",
            "content": "作者の趣味で着ている"
        }        
    ]
}

### person.update
PUT {{host}}/api/person/id/e66e343a-5e2f-4053-8e2b-1185e8faef88

{
    "provider": "provider",
    "name": "hoge",
    "roles": [
        0
    ],
    "machines": [
        {
            "id": "MachineId",
            "name": "MachineName"
        },
        {
            "id": "MachineId2",
            "name": "MachineName2"
        }
    ]
}