@host = http://localhost:7071

### person.index
GET {{host}}/api/person

### person.index
GET {{host}}/api/person?name=放

### person.index
GET {{host}}/api/person?name=軍師

### person.index
GET {{host}}/api/person?job=アプリケーション

### person.index
GET {{host}}/api/person?attribute=ランダム

### person.show
GET {{host}}/api/person/id/b0e6177f-27ce-46f1-8743-fdd32a964754

### person.show
GET {{host}}/api/person/エンジニア/b0e6177f-27ce-46f1-8743-fdd32a964754

### person.delete
DELETE {{host}}/api/person/エンジニア/75e1c441-9e94-4dae-9556-17bc16773c31

### person.store
POST {{host}}/api/person

{
    "name": "放浪軍師",
    "job": "エンジニア",
    "attributes": [
        "変態","変人"
    ],
    "items":[
        {
            "name": "デスクトップパソコン",
            "content": "VRやるためにそこそこのしたヤツ"
        },
        {
            "name": "ノートパソコン",
            "content": "乱ちゃんのシールが貼ってあるMACPC"
        }        
    ]
}

### person.store
POST {{host}}/api/person

{
    "name": "夏狂乱",
    "job": "アプリケーション",
    "attributes": [
        "ランダム","マルチプラットフォーム","抽選"
    ],
    "items":[
        {
            "name": "サイコロ",
            "content": "髪飾りに2個付いている"
        },
        {
            "name": "巫女服",
            "content": "作者の趣味で着ている"
        }        
    ]
}

### person.store
POST {{host}}/api/person

{
    "name": "漆原鎌足",
    "job": "エンジニア",
    "attributes": [
        "退魔士","ゲーム","VTuber"
    ],
    "items":[
        {
            "name": "日本刀",
            "content": "沢山差している"
        }        
    ]
}

### person.update
PUT {{host}}/api/person/id/c6bde71e-361c-447d-a096-95d6bb4603a7

{
    "name": "放浪群子",
    "job": "aaa",
    "attributes": [
        "変態","変人"
    ],
    "items":[
        {
            "name": "デスクトップパソコン",
            "content": "VRやるためにそこそこのしたヤツ"
        }
    ]
}